Fix upload logfiles as artifact

diff --git a/tests/testconfig/.gitlab-ci.yml b/tests/testconfig/.gitlab-ci.yml
--- a/tests/testconfig/.gitlab-ci.yml
+++ b/tests/testconfig/.gitlab-ci.yml
@@ -93,39 +93,38 @@ before_script:
 - echo Building the following targets ${BUILD_TARGETS}
   # build
 - time ${CMAKE_COMMAND} --build . --target ${BUILD_TARGETS} -- -j `nproc` 2>&1 | tee
-  build.log
+  ${CI_PROJECT_DIR}/build.log
 
 .build-and-test: &build-and-test
 - *build-only
   # test
 - 'echo ctest selection: $CTEST_TEST_SELECTION'
 - time ${CTEST_COMMAND} -VV $CTEST_TEST_SELECTION -j `nproc` --output-junit ${CI_PROJECT_DIR}/junit_test_summary.xml
-  | tee test.log | grep -e "\*\*\*Failed" -e "\.\.\.   Passed" -e " tests passed\,"
+  | tee ${CI_PROJECT_DIR}/test.log | grep -e "\*\*\*Failed" -e "\.\.\.   Passed" -e
+  " tests passed\,"
 - cd ${CI_PROJECT_DIR}
 
 .check-no-warnings: &check-no-warnings
 - cd ${CI_PROJECT_DIR}/../baci-build
   # check for warnings
-- if grep -iP "warning:" build.log; then echo 'Warnings found!' && exit 1; else echo
-  'No warnings found'; fi
+- if grep -iP "warning:" ${CI_PROJECT_DIR}/build.log; then echo 'Warnings found!'
+  && exit 1; else echo 'No warnings found'; fi
 - cd ${CI_PROJECT_DIR}
 
 .post-process-log-files: &post-process-log-files
   # sort output of pipeline
 - cd ${CI_PROJECT_DIR}/../baci-build
 - ${CI_PROJECT_DIR}/utilities/baci-python-venv/bin/python ${CI_PROJECT_DIR}/utilities/sort_pipeline_output.py
-  test.log test.log
+  ${CI_PROJECT_DIR}/test.log ${CI_PROJECT_DIR}/test.log
   # Write selection of the output into the terminal and therefore to GITLAB
   # Output 200 lines for any failing test
-- grep -B 200 '*Failed\|*Timeout' test.log || true
-- sed -n '/tests passed,/,//p' test.log
+- grep -B 200 '*Failed\|*Timeout' ${CI_PROJECT_DIR}/test.log || true
+- sed -n '/tests passed,/,//p' ${CI_PROJECT_DIR}/test.log
   # Specify which configuration was tested by this pipeline
 - 'echo Baci build type: $CTEST_BUILD_TYPE_GITLAB'
 - 'echo Run tests matching expression: $TEST_TAG [{.} all tests, {} no test]'
 - 'echo Excluded tests: $CTEST_EXCLUDE_STRING [{} no test excluded]'
   # Move the log files to the source folder, so it can be found by artifacts.
-- mv build.log ${CI_PROJECT_DIR}/
-- mv test.log ${CI_PROJECT_DIR}/
 - cd ${CI_PROJECT_DIR}
 
 
@@ -177,19 +176,19 @@ before_script:
   - *build-and-test
     # generate the baci_coverage_base.info: the "baseline" coverage data file that contains zero coverage for every instrumented line.
   - lcov --capture --initial --no-external --directory ../baci-build/ --base-directory
-    . --output-file baci_coverage_base.info > baci_coverage_base.log
+    . --output-file baci_coverage_base.info > ${CI_PROJECT_DIR}/baci_coverage_base.log
     # generate the baci_coverage_tests.info based on tests run above
   - lcov --capture --no-external --directory ../baci-build/ --base-directory . --output-file
-    baci_coverage_tests.info > baci_coverage_tests.log
+    baci_coverage_tests.info > ${CI_PROJECT_DIR}/baci_coverage_tests.log
     # combine the baseline coverage with the coverage from the tests
   - lcov --add-tracefile baci_coverage_base.info --add-tracefile baci_coverage_tests.info
-    --output-file baci_coverage.info  > baci_coverage.log
+    --output-file baci_coverage.info  > ${CI_PROJECT_DIR}/baci_coverage.log
     # remove unwanted files from the coveragre report
   - lcov --remove baci_coverage.info "*/unittests*/*" "*/tests/*" "*/baci-build/*"
-    -o baci_coverage_filtered.info > baci_coverage_filtered.log
+    -o baci_coverage_filtered.info > ${CI_PROJECT_DIR}/baci_coverage_filtered.log
     # generate the html version of the coverage report
   - genhtml baci_coverage_filtered.info --legend --demangle-cpp --output-directory
-    coverage_report/ --title "BACI commit $CI_COMMIT_SHORT_SHA" | tee genhtml_coverage.log
+    coverage_report/ --title "BACI commit $CI_COMMIT_SHORT_SHA" | tee ${CI_PROJECT_DIR}/genhtml_coverage.log
     # add repo link to the commit that the report is based on
   - find coverage_report/ -type f -exec sed -i "s/BACI commit $CI_COMMIT_SHORT_SHA/BACI
     commit  \<a 
@@ -280,24 +279,25 @@ before_script:
     # Configure and build (setting BACI_BUILD_READTHEDOCS=OFF, so that we don't need the python virtual environment
   - ${CMAKE_COMMAND} ${CI_PROJECT_DIR} --preset=${CTEST_BUILD_PRESETS_RELEASE_GITLAB}
     -DBACI_BUILD_READTHEDOCS=OFF
-  - ${CMAKE_COMMAND} --build . --target doxygen > ../doxygen.log
+  - ${CMAKE_COMMAND} --build . --target doxygen > ${CI_PROJECT_DIR}/doxygen.log
 
     # Throw error if there are Latex errors in doxygen comments. Latex errors can be uniquely identified by a line starting with "! ".
-  - if grep -qE '^[eE]rror:' ../doxygen.log; then echo 'Found at least one fatal error
-    during doxygen generation.'; exit 1; else echo 'Doxygen builds without fatal errors.';
-    fi
-  - if grep -qE '^! ' ../doxygen.log; then echo "Found at least one LaTeX error during
-    doxygen build."; exit 1; else echo "Doxygen builds without LaTeX errors."; fi
+  - if grep -qE '^[eE]rror:' ${CI_PROJECT_DIR}/doxygen.log; then echo 'Found at least
+    one fatal error during doxygen generation.'; exit 1; else echo 'Doxygen builds
+    without fatal errors.'; fi
+  - if grep -qE '^! ' ${CI_PROJECT_DIR}/doxygen.log; then echo "Found at least one
+    LaTeX error during doxygen build."; exit 1; else echo "Doxygen builds without
+    LaTeX errors."; fi
     # Move final doxygen into the base folder for the next stage
   - mv $CI_PROJECT_DIR/../baci-build/doc/doxygen/html $CI_PROJECT_DIR/doxygen
   after_script:
     # Write Selection of the output into the terminal and therefore to GITLAB
-  - sed -n '/* Extra verbosity turned on/,/Test project /p' ../doxygen.log
+  - sed -n '/* Extra verbosity turned on/,/Test project /p' ${CI_PROJECT_DIR}/doxygen.log
     # Write information about possible Latex errors to terminal
-  - if grep -qE '^! ' ../doxygen.log; then echo "Found at least one LaTeX error during
-    doxygen build."; else echo "Doxygen builds without LaTeX errors."; fi
+  - if grep -qE '^! ' ${CI_PROJECT_DIR}/doxygen.log; then echo "Found at least one
+    LaTeX error during doxygen build."; else echo "Doxygen builds without LaTeX errors.";
+    fi
     # Move the log file to the source folder, so it can be found by artifacts.
-  - mv ../doxygen.log doxygen.log
   variables:
     CTEST_BUILD_PRESETS_RELEASE_GITLAB: docker
     CMAKE_COMMAND: cmake
@@ -316,19 +316,18 @@ before_script:
 
     # Configure and build
   - ${CMAKE_COMMAND} ${CI_PROJECT_DIR} --preset=${CTEST_BUILD_PRESETS_RELEASE_GITLAB}
-  - ${CMAKE_COMMAND} --build . --target readthedocs | tee ../readthedocs.log
+  - ${CMAKE_COMMAND} --build . --target readthedocs | tee ${CI_PROJECT_DIR}/readthedocs.log
 
     # Throw error if there are errors (or Warnings treated as errors) in readthedocs comments.
-  - if grep -qE 'ERROR|treated as error:' ../readthedocs.log; then echo 'Found at
-    least one fatal error during readthedocs generation.'; exit 1; else echo 'ReadTheDocs
-    documentation builds without fatal errors.'; fi
+  - if grep -qE 'ERROR|treated as error:' ${CI_PROJECT_DIR}/readthedocs.log; then
+    echo 'Found at least one fatal error during readthedocs generation.'; exit 1;
+    else echo 'ReadTheDocs documentation builds without fatal errors.'; fi
     # Move final readthedocs into the base folder for the next stage
   - mv $CI_PROJECT_DIR/../baci-build/doc/readthedocs/html $CI_PROJECT_DIR/readthedocs
   after_script:
     # Write Selection of the output into the terminal and therefore to GITLAB
-  - sed -n '/* Extra verbosity turned on/,/Test project /p' ../readthedocs.log
+  - sed -n '/* Extra verbosity turned on/,/Test project /p' ${CI_PROJECT_DIR}/readthedocs.log
     # Move the log file to the source folder, so it can be found by artifacts.
-  - mv ../readthedocs.log readthedocs.log
   variables:
     CTEST_BUILD_PRESETS_RELEASE_GITLAB: docker
     CMAKE_COMMAND: cmake
@@ -597,7 +596,8 @@ buildtest_full_release_asan:
     CTEST_COMMAND: ctest
   after_script:
   - *post-process-log-files
-  - ${CI_PROJECT_DIR}/utilities/grep_asan_failures.sh test.log > asan_summary.log
+  - ${CI_PROJECT_DIR}/utilities/grep_asan_failures.sh ${CI_PROJECT_DIR}/test.log >
+    ${CI_PROJECT_DIR}/asan_summary.log
   tags:
   - buildtest
   needs:
@@ -648,7 +648,7 @@ build-verify-headers:
     ${CMAKE_COMMAND} ${CI_PROJECT_DIR} --preset=docker -DCMAKE_VERIFY_INTERFACE_HEADER_SETS="ON"
     # verify headers
   - time ${CMAKE_COMMAND} --build . --target all_verify_interface_header_sets -- -j
-    `nproc` 2>&1 | tee verify_headers.log
+    `nproc` 2>&1 | tee ${CI_PROJECT_DIR}/verify_headers.log
   artifacts:
     name: $CI_JOB_NAME-$CI_JOB_ID
     paths:
