Use ccache by default

diff --git a/do-configure b/do-configure
--- a/do-configure
+++ b/do-configure
@@ -14,6 +14,7 @@ USE_ACML=0
 USE_FORCEBUILD=0
 TRILINOS_EXPERIMENTAL=0  # use experimental Trilinos version (e.g. current state of develop)
 SHARED_LIBS=OFF
+CCACHE_COMMAND=ccache
 
 USE_TRILINOS_Q1_2015=OFF
 USE_TRILINOS_Q1_2019=OFF
@@ -33,11 +34,11 @@ USE_TRILINOS_Q1_2019=OFF
 # testing is achieved by setting '--debug-optimized'
 # Note: Use only one of them! No checks in place if both are specified.
 
-OPTIONS=`getopt -o hc:daef -l help,config:,debug,debug-optimized,trilinos-debug,profiling,coverage,useACML,experimental,forceBuild,ide: -- "$@"`
+OPTIONS=`getopt -o hc:daef -l help,config:,debug,debug-optimized,trilinos-debug,profiling,coverage,useACML,experimental,forceBuild,no-ccache,ide: -- "$@"`
 
 [ $? -ne 0 ] && exit 1
 
-USAGEINFO="usage: do-configure --config=configurationfile [--debug] [--debug-optimized] [--trilinos-debug] [--profiling] [--coverage] [--experimental] [--useACML] [--forceBuild] [--ide=clion/eclipse/vscode]"
+USAGEINFO="usage: do-configure --config=configurationfile [--debug] [--debug-optimized] [--trilinos-debug] [--profiling] [--coverage] [--experimental] [--useACML] [--forceBuild] [--ide=clion/eclipse/vscode] [--no-ccache]"
 
 eval set -- $OPTIONS
 
@@ -75,6 +76,9 @@ while true; do
       ;;
     -f|--forceBuild)
       USE_FORCEBUILD=1
+      ;;
+    --no-ccache)
+      CCACHE_COMMAND=""
       ;;
     --ide)
       ADAPT_IDE_CLION=0
@@ -141,6 +145,19 @@ fi
 
 # set valid folder for baci build
 BUILD_FOLDER=$BUILD_FOLDER_SAFE
+
+
+##############################################################
+# Check if ccache is installed
+if [[ $CCACHE_COMMAND != "" ]]; then
+    if ! command -v $CCACHE_COMMAND &> /dev/null
+    then
+        echo "ccache command: $CCACHE_COMMAND could not be found, ccache will not be used!"
+        exit
+    fi
+fi
+
+
 
 ##############################################################
 # Print source and build folder locations to screen
@@ -247,6 +264,7 @@ CMAKE_FULL_ARGS=(--no-warn-unused-cli \
   -D BLAS_LIBRARIES:FILEPATH="$BLAS_LIBS" \
   -D LAPACK_LIBRARIES:FILEPATH="$LAPACK_LIBS" \
   -D ACMLDIR:STRING="$ACMLDIR_PATH" \
+  -D CMAKE_CXX_COMPILER_LAUNCHER="$CCACHE_COMMAND" \
   -D AMDLIBMDIR:FILEPATH="$AMDLIBMDIR_PATH" \
   "$EXTRA_ARGS" \
   "${BACI_HOME}")
