New BINIO version. Explicit element variants have been removed. The filter have been improved.
This is still a developement version. Old BINIO files are no longer
supported.


git-svn-id: svn://jacobi.lnm.mw.tum.de/baci/trunk/ccarat@1905 060e22d8-9d1c-0410-868a-e3a950d63d95

diff --git a/run_test b/run_test
--- a/run_test
+++ b/run_test
@@ -54,10 +54,18 @@ function cleanup
 
     # remove hook
     trap "echo" 0 1 2 15
-    #exit
 }
 
-trap "cleanup" 0 1 2 15
+function exittrap
+{
+    cleanup
+
+    # If we exit here something went wrong.
+    # (It might have been a user interupt.)
+    exit 1
+}
+
+trap "exittrap" 0 1 2 15
 
 
 # remove all output files from previous runs
@@ -224,6 +232,9 @@ fi
 printf $fail2'  |\n'
 echo '-----------------------------'
 echo
+
+# We are done. Clean up and remove the exit trap.
+cleanup
 
 # exit with non-zero return code if something went wrong
 if [ $fail1 -ge 1 ]; then
