- binary io update - new filters (monitor and visual2) - levelset traces removed
git-svn-id: svn://jacobi.lnm.mw.tum.de/baci/trunk/ccarat@1891 060e22d8-9d1c-0410-868a-e3a950d63d95

diff --git a/run_test b/run_test
--- a/run_test
+++ b/run_test
@@ -54,7 +54,7 @@ function cleanup
 
     # remove hook
     trap "echo" 0 1 2 15
-    exit
+    #exit
 }
 
 trap "cleanup" 0 1 2 15
@@ -224,3 +224,11 @@ fi
 printf $fail2'  |\n'
 echo '-----------------------------'
 echo
+
+# exit with non-zero return code if something went wrong
+if [ $fail1 -ge 1 ]; then
+  exit 1
+fi
+if [ $fail2 -ge 1 ]; then
+  exit 1
+fi
